# Generated by Django 3.1.1 on 2020-10-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20201015_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeType',
            field=models.CharField(choices=[('1', 'Potential'), ('5', 'Executive'), ('3', 'Salaried'), ('4', 'Manager'), ('2', 'Hourly')], default='1', max_length=20),
        ),
    ]
