# Generated by Django 3.1.1 on 2020-10-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20201016_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeType',
            field=models.CharField(choices=[('4', 'Manager'), ('1', 'Potential'), ('3', 'Salaried'), ('5', 'Executive'), ('2', 'Hourly')], default='1', max_length=20),
        ),
    ]
