# Generated by Django 3.1.1 on 2020-10-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20201017_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeType',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('potential', 'Potential'), ('executive', 'Executive'), ('salaried', 'Salaried'), ('manager', 'Manager')], default='1', max_length=20),
        ),
    ]
