# Generated by Django 3.1.1 on 2020-10-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20201019_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeType',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('manager', 'Manager'), ('executive', 'Executive'), ('potential', 'Potential'), ('salaried', 'Salaried')], default='potential', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastName',
            field=models.CharField(max_length=200),
        ),
    ]
