# Generated by Django 3.1.1 on 2020-10-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20201019_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='notes',
            new_name='cur_assignment',
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeType',
            field=models.CharField(choices=[('salaried', 'Salaried'), ('executive', 'Executive'), ('manager', 'Manager'), ('hourly', 'Hourly'), ('potential', 'Potential')], default='potential', max_length=20),
        ),
    ]
