# Generated by Django 3.1.1 on 2020-10-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_auto_20201024_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeType',
            field=models.CharField(choices=[('executive', 'Executive'), ('potential', 'Potential'), ('salaried', 'Salaried'), ('manager', 'Manager'), ('hourly', 'Hourly')], default='potential', max_length=20),
        ),
    ]
