# Generated by Django 3.1.1 on 2020-10-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_auto_20201028_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emergencyContact',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeType',
            field=models.CharField(choices=[('potential', 'Potential'), ('manager', 'Manager'), ('hourly', 'Hourly'), ('executive', 'Executive'), ('salaried', 'Salaried')], default='potential', max_length=20),
        ),
    ]
