# Generated by Django 3.1.1 on 2020-11-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_auto_20201031_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='birthdate',
            new_name='birthDate',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeType',
            field=models.CharField(choices=[('manager', 'Manager'), ('executive', 'Executive'), ('potential', 'Potential'), ('hourly', 'Hourly'), ('salaried', 'Salaried')], default='potential', max_length=20),
        ),
    ]
