# Generated by Django 3.1.1 on 2020-11-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_auto_20201102_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeType',
            field=models.CharField(choices=[('salaried', 'Salaried'), ('potential', 'Potential'), ('hourly', 'Hourly'), ('manager', 'Manager'), ('executive', 'Executive')], default='potential', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(default='static/240x240_default_img.jpg', upload_to='employees/images/'),
        ),
    ]
