# Generated by Django 3.1.1 on 2020-11-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_auto_20201102_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeType',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('manager', 'Manager'), ('potential', 'Potential'), ('executive', 'Executive'), ('salaried', 'Salaried')], default='potential', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, default='static/240x240_default_img.jpg', upload_to='employees/images/'),
        ),
    ]
