# Generated by Django 3.1.1 on 2020-11-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_auto_20201102_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeType',
            field=models.CharField(choices=[('potential', 'Potential'), ('salaried', 'Salaried'), ('hourly', 'Hourly'), ('manager', 'Manager'), ('executive', 'Executive')], default='potential', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, default='employees/images/240x240_default_img.jpg', upload_to='employees/images/'),
        ),
    ]
