# Generated by Django 3.1.1 on 2020-11-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_auto_20201105_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeType',
            field=models.CharField(choices=[('executive', 'Executive'), ('hourly', 'Hourly'), ('potential', 'Potential'), ('manager', 'Manager'), ('salaried', 'Salaried')], default='potential', max_length=20),
        ),
    ]
