# Generated by Django 3.1.1 on 2020-11-06 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_auto_20201106_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='exp_list',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_list',
        ),
        migrations.AddField(
            model_name='experience',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AddField(
            model_name='skill',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeType',
            field=models.CharField(choices=[('potential', 'Potential'), ('hourly', 'Hourly'), ('executive', 'Executive'), ('salaried', 'Salaried'), ('manager', 'Manager')], default='potential', max_length=20),
        ),
        migrations.DeleteModel(
            name='ExperienceList',
        ),
        migrations.DeleteModel(
            name='SkillsList',
        ),
    ]
