# Generated by Django 3.1.1 on 2020-12-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_auto_20201112_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeType',
            field=models.CharField(choices=[('potential', 'Potential'), ('salaried', 'Salaried'), ('manager', 'Manager'), ('hourly', 'Hourly'), ('executive', 'Executive')], default='potential', max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='from_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='to_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='rank',
            field=models.CharField(choices=[('expert', 'Expert'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('novice', 'Novice')], default='novice', max_length=50),
        ),
    ]
