# Generated by Django 3.1.1 on 2020-12-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0026_auto_20201204_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeType',
            field=models.CharField(choices=[('manager', 'Manager'), ('salaried', 'Salaried'), ('executive', 'Executive'), ('potential', 'Potential'), ('hourly', 'Hourly')], default='potential', max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='to_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='rank',
            field=models.CharField(choices=[('advanced', 'Advanced'), ('expert', 'Expert'), ('intermediate', 'Intermediate'), ('novice', 'Novice')], default='novice', max_length=50),
        ),
    ]
