# Generated by Django 3.1.1 on 2020-12-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_auto_20201204_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeType',
            field=models.CharField(choices=[('executive', 'Executive'), ('potential', 'Potential'), ('manager', 'Manager'), ('hourly', 'Hourly'), ('salaried', 'Salaried')], default='potential', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='rank',
            field=models.CharField(choices=[('expert', 'Expert'), ('novice', 'Novice'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='novice', max_length=50),
        ),
    ]
